SHOW DATABASES ;
# CREATE DATABASE HOSPITAL_BED_AVAILIBILITY;
# USE HOSPITAL_BED_AVAILIBILITY;
SHOW TABLES;

/*
CREATE TABLE BEDS(
    HOSPITAL_ID INTEGER,
    PATIENT_ID INTEGER PRIMARY KEY,
    DISEASE VARCHAR(40),
    DAYS_BED_AVAILIBILITY INTEGER
                 );
*/


CREATE TABLE PATIENT(
    S_NO INTEGER PRIMARY KEY,
    NAME VARCHAR(40),
    BLOOD_GROUP VARCHAR(40),
    DIABETES VARCHAR(40),
    AREA_PIN_CODE INTEGER
                    );

SELECT *FROM PATIENT;









